---
title: "Análisis y visualización"
format: html
execute:
  freeze: false

---
## Introducción

Esta sección presenta el análisis visual de la evolución de la pobreza en el Ecuador entre 2019 y 2025, utilizando los datos de la ENEMDU previamente limpiados y transformados.
Para garantizar que los resultados sean representativos de la población nacional, las estimaciones se construyen utilizando el **factor de expansión (`fexp`)** proporcionado por el INEC.
 
``` {python}
#| echo: false
#| warning: false
#| message: false

import pandas as pd
import altair as alt
from PIL import Image
import matplotlib.pyplot as plt 
import json
from collections import defaultdict

alt.data_transformers.disable_max_rows()
df = pd.read_csv("./basesdedatos/ENEMDU_2019-2025_CLEAN.csv")
df["periodo"] = df["periodo"].astype(int)
df["fexp"] = pd.to_numeric(df["fexp"])
```
## Evolución de la pobreza y pobreza extrema (2019–2025)

**Pregunta analítica:**  
¿Cómo ha evolucionado la pobreza y la pobreza extrema en el Ecuador antes y después de la pandemia?

### Visualización utilizada
```{python}
#| echo: false
#| warning: false
#| message: false
pobreza_anual = (
    df
    .assign(
        pobreza_w = df["pobreza"] * df["fexp"],
        epobreza_w = df["epobreza"] * df["fexp"]
    )
    .groupby("periodo", as_index=False)
    .agg(
        pobreza=("pobreza_w", "sum"),
        pobreza_extrema=("epobreza_w", "sum"),
        total=("fexp", "sum")
    )
)
pobreza_anual["pobreza"] = pobreza_anual["pobreza"] / pobreza_anual["total"]
pobreza_anual["pobreza extrema"] = pobreza_anual["pobreza_extrema"] / pobreza_anual["total"]

pobreza_long = pobreza_anual.melt(
    id_vars="periodo",
    value_vars=["pobreza", "pobreza extrema"],
    var_name="tipo",
    value_name="tasa"
)
chart=alt.Chart(pobreza_long, title="Evolución de la pobreza en el Ecuador (2019–2025)").mark_line(point=True).encode(
    x=alt.X("periodo:O", title="Año"),
    y=alt.Y("tasa:Q", title="Tasa de pobreza", axis=alt.Axis(format=".0%")),
    color=alt.Color("tipo:N", title="Indicador"),
    tooltip=["periodo", alt.Tooltip("tasa:Q", format=".1%")]
).properties(
    width='container'
).interactive()
chart 
```
### Interpretación

El gráfico evidencia un quiebre significativo en el período 2020, coincidiendo con el impacto económico y social de la pandemia de COVID-19. Tanto la pobreza como la pobreza extrema aumentan de forma pronunciada respecto a 2019, pasando aproximadamente de 25 % a más de 32 % en pobreza y de 9 % a cerca de 15 % en pobreza extrema

En los años posteriores se observa una reducción gradual, aunque los niveles previos a la pandemia no se recuperan hasta 2025, lo que sugiere efectos persistentes de la crisis sobre las condiciones de vida de las personas. En 2023 y 2024 se observa una dinámica inestable, con un nuevo repunte de la pobreza y, especialmente, de la pobreza extrema en 2024.
 
## Diferencias entre variables demográficas {.tabset}

**Pregunta analítica:**  
¿Existen diferencias en los niveles de pobreza entre variables demográficas como etnia, edad o área de residencia?
 
```{python}
#| echo: false
#| warning: false
#| message: false   

def grafico_pobreza(df, grupo, titulo, nombre_archivo):
    tabla = (
        df
        .assign(pobreza_w=df["pobreza"] * df["fexp"])
        .groupby(grupo, as_index=False)
        .agg(
            pobreza=("pobreza_w", "sum"),
            total=("fexp", "sum")
        )
    )
    tabla["tasa"] = tabla["pobreza"] / tabla["total"]
    if nombre_archivo == "pobreza_edad":
        orden = [
            "0–14", "15–24", "25–34",
            "35–44", "45–54", "55–64",
            "65–74", "75–84", "85+"
        ]
        y_enc = alt.Y(
            f"{grupo}:N",
            sort=orden,
            title="Grupo de edad"
        )
    else:
        y_enc = alt.Y(
            f"{grupo}:N",
            sort="-x",
            title=grupo
        )

    chart = (
        alt.Chart(tabla, title=titulo)
        .mark_bar()
        .encode(
            x=alt.X(
                "tasa:Q",
                title="Tasa de pobreza",
                axis=alt.Axis(format=".0%")
            ),
            y=y_enc,
            tooltip=[
                grupo,
                alt.Tooltip("tasa:Q", format=".1%")
            ]
        )
    )

    return chart

df.rename(columns={'nnivins':'Nivel de instrucción',
'area':'Área de residencia',
'p15':'Etnia',
'p02':'Sexo'},inplace=True)    
```
### Área de residencia

```{python}
#| echo: false
#| warning: false
#| message: false   

c=grafico_pobreza(
    df,
    grupo='Área de residencia',
    titulo="Tasa de pobreza por área de residencia",
    nombre_archivo="pobreza_area"
).properties(
    width='container'
).interactive()
c
```
### Etnia

```{python}
#| echo: false
#| warning: false
#| message: false
c=grafico_pobreza(
    df[~df['Etnia'].isin(['OTRA','MENOR DE 5 AÑOS'])],
    grupo='Etnia',
    titulo="Tasa de pobreza por etnia",
    nombre_archivo="pobreza_etnia"
).properties(
    width='container'
).interactive()
c
```
### Nivel de instrucción
```{python}
#| echo: false
#| warning: false
#| message: false
c=grafico_pobreza(
    df,
    grupo='Nivel de instrucción',
    titulo="Tasa de pobreza por nivel de instrucción",
    nombre_archivo="pobreza_educacion"
).properties(
    width='container'
).interactive()
c
```
### Grupo Etario
```{python}
#| echo: false
#| warning: false
#| message: false
df["edad_grupo"] = pd.cut(
    df["p03"].astype(int),
    bins=[0,14, 24, 34, 44, 54, 64,74,84, 120],
    labels=[
        "0–14", "15–24", "25–34",
        "35–44", "45–54", "55–64", "65–74","75–84","85+"
    ],  
    include_lowest=True
)
orden_edades=[
        "0–14", "15–24", "25–34",
        "35–44", "45–54", "55–64", "65–74","75–84","85+"
    ]
df["edad_grupo"] = pd.Categorical(
    df["edad_grupo"],
    categories=orden_edades,
    ordered=True
)
c=grafico_pobreza(
    df,
    grupo="edad_grupo",
    titulo="Tasa de pobreza por grupo de edad",
    nombre_archivo="pobreza_edad"
).properties(
    width='container'
).interactive() 
c
```
 
### Interpretación

En conjunto, los gráficos muestran que la pobreza en Ecuador (2019–2026) no se distribuye aleatoriamente, sino que sigue ejes estructurales bien definidos:

- Territorio (rural)
- Etnia (indígena, negra, afroecuatoriana)
- Educación (bajo nivel educativo)
- Ciclo de vida (niñez y vejez)

Tiende a acumularse en los mismos grupos, generando trampas de pobreza intergeneracional, por lo que su reducción requiere intervenciones integrales en acceso a educación de calidad, desarrollo rural, inclusión étnica efectiva y protección social a lo largo del toda de vida.

## Pobreza y condiciones laborales

**Pregunta analítica:**  
¿Cómo se relaciona la pobreza con la situación laboral de las personas?

***
###  Pobreza por tipo de empleo 

```{python}
#| echo: false
#| warning: false
#| message: false  
  
df_pobres = df[df["pobreza"] == 1].copy() 
df_pobres = df[df["condact"] != 'SIN EMPLEO'].copy() 
df_pobres = df[df["secemp"] != 'SIN EMPLEO'].copy() 
heatmap_data = (
    df_pobres
    .groupby(["condact", "secemp"], as_index=False)
    .agg(personas_pobres=("fexp", "sum"))
)
heatmap = (
    alt.Chart(heatmap_data)
    .mark_rect()
    .encode(
        x=alt.X(
            "condact:N",
            title="Condición de actividad"
        ),
        y=alt.Y(
            "secemp:N",
            title="Sector de empleo"
        ),
        color=alt.Color(
            "personas_pobres:Q",
            title="Personas pobres",
            scale=alt.Scale(scheme="reds")
        ),
        tooltip=[
            alt.Tooltip("condact:N", title="Condición"),
            alt.Tooltip("secemp:N", title="Sector"),
            alt.Tooltip("personas_pobres:Q", title="Personas pobres", format=",.0f")
        ]
    )
    .properties( 
        title="Personas pobres por condición de actividad y sector de empleo"
    ) 
).properties(
        width='container').interactive()
heatmap
```
 
```{python}
#| echo: false
#| warning: false
#| message: false  
 
# Crear parámetro interactivo para el año
anio_selector = alt.param(
    name="Año",
    bind=alt.binding_select(
        options=sorted(df_pobres["periodo"].unique().tolist()),
        name="Seleccione año: "
    ),
    value=sorted(df_pobres["periodo"].unique())[0]
)

# Agregar año al agrupamiento
heatmap_data = (
    df_pobres
    .groupby(["periodo", "condact", "secemp"], as_index=False)
    .agg(personas_pobres=("fexp", "sum"))
)

# Heatmap
heatmap = (
    alt.Chart(heatmap_data)
    .add_params(anio_selector)
    .transform_filter(alt.datum.periodo == anio_selector)
    .mark_rect()
    .encode(
        x=alt.X(
            "condact:N",
            title="Condición de actividad"
        ),
        y=alt.Y(
            "secemp:N",
            title="Sector de empleo"
        ),
        color=alt.Color(
            "personas_pobres:Q",
            title="Personas pobres",
            scale=alt.Scale(scheme="reds")
        ),
        tooltip=[
            alt.Tooltip("condact:N", title="Condición"),
            alt.Tooltip("secemp:N", title="Sector"),
            alt.Tooltip("personas_pobres:Q", title="Personas pobres", format=",.0f")
        ]
    )
    .properties(
        title="Personas pobres por condición de actividad y sector de empleo",
        width="container"
    )
)

heatmap
```
***
###  Pobreza por tipo de actividad
```{python}
#| echo: false
#| warning: false
#| message: false  
  
df_pobres = df[df["pobreza"] == 1].copy() 
df_pobres = df[df["condact"] != 'SIN EMPLEO'].copy() 
df_pobres = df[df["secemp"] != 'SIN EMPLEO'].copy() 

heatmap_data = (
    df_pobres
    .groupby(["grupo1", "rama1"], as_index=False)
    .agg(personas_pobres=("fexp", "sum"))
)
heatmap = (
    alt.Chart(heatmap_data)
    .mark_rect()
    .encode(
        x=alt.X(
            "grupo1:N",
            title="Grupo Ocupacional"
        ),
        y=alt.Y(
            "rama1:N",
            title="Rama de actividad"
        ),
        color=alt.Color(
            "personas_pobres:Q",
            title="Personas pobres",
            scale=alt.Scale(scheme="reds")
        ),
        tooltip=[
            alt.Tooltip("grupo1:N", title="Grupo ocupacional"),
            alt.Tooltip("rama1:N", title="Rama de actividad"),
            alt.Tooltip("personas_pobres:Q", title="Personas pobres", format=",.0f")
        ]
    )
    .properties( 
        title="Personas pobres por grupo ocupacional y rama de actividad"
    ) 
).properties(
        width='container').interactive()
heatmap
```

### Interpretación

La pobreza se concentra en personas desempleadas o con empleo precario, especialmente en el sector informal. Esto muestra que no basta con tener empleo: la calidad del trabajo es un factor clave para reducir la pobreza por ingresos.

Además, la pobreza se concentra principalmente en actividades como agricultura, comercio, construcción y servicios, especialmente entre ocupaciones no calificadas. Esto evidencia que los sectores de baja productividad y alta informalidad agrupan a la mayor población pobre.
 